
services:
  # MySQL 数据库服务
  mysql-db:
    image: mysql:8.0
    container_name: cv_infer_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678jmp
      MYSQL_DATABASE: cv_infer
    ports:
      - "3306:3306"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql # 自动执行建表语句
    networks:
      - cv-network
     # 新增健康检查，每 5 秒探查一次 MySQL 是否准备好
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678jmp"]
      interval: 5s
      timeout: 5s
      retries: 10

  # C++ AI 推理网关服务
  cv-infer-gate:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: cv_infer_gate
    ports:
      - "50051:50051"
    depends_on:
      mysql-db:
        condition: service_healthy # 等 mysql-db 健康检查通过后再启动
    # depends_on:
    #   - mysql-db
    networks:
      - cv-network
    # # 覆盖配置文件里的数据库地址，指向 docker 网络内的 mysql 服务
    # environment:
    #   - DB_HOST=tcp://mysql-db:3306
    # 注意：程序目前是读 config.yaml，如果要在 docker 里动态改，需要在代码里支持环境变量，或者挂载 config 文件
    volumes:
      - ../config:/app/config
      - ../models:/app/models
      - ../test.mp4:/app/test.mp4 
      - ../output:/app/output  # 拿到处理后的视频

networks:
  cv-network:
    driver: bridge