video:
  source_type: "file"        # 可选：file 或 rtsp
  # source_path: "test.mp4"    # 视频文件路径或 RTSP 地址  /app/test.mp4
  source_path: "../test.mp4"    # 视频文件路径或 RTSP 地址  /app/test.mp4

database:
  host: "mysql-db:3306"
  # host: "tcp://mysql-db:3306"
  user: "root"
  password: "input your password"
  dbname: "cv_infer"

grpc:
  port: 50051