//protobuff的中间件


syntax = "proto3";

package inference;

// 定义检测请求
message DetectRequest {
    bytes image_data = 1;  // 图片的二进制数据（比如 JPEG 编码的字节流）
}

// 定义单个检测结果
message Detection {
    int32 class_id = 1;
    string label = 2;
    float confidence = 3;
    int32 x1 = 4;
    int32 y1 = 5;
    int32 x2 = 6;
    int32 y2 = 7;
}

// 定义检测响应
message DetectResponse {
    bool success = 1;
    string message = 2;
    repeated Detection detections = 3;
}

// 定义 gRPC 服务
service DetectionService {
    rpc Detect (DetectRequest) returns (DetectResponse);
}