# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"#\n\rDetectRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"p\n\tDetection\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\n\n\x02x1\x18\x04 \x01(\x05\x12\n\n\x02y1\x18\x05 \x01(\x05\x12\n\n\x02x2\x18\x06 \x01(\x05\x12\n\n\x02y2\x18\x07 \x01(\x05\"\\\n\x0e\x44\x65tectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12(\n\ndetections\x18\x03 \x03(\x0b\x32\x14.inference.Detection2Q\n\x10\x44\x65tectionService\x12=\n\x06\x44\x65tect\x12\x18.inference.DetectRequest\x1a\x19.inference.DetectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTREQUEST']._serialized_start=30
  _globals['_DETECTREQUEST']._serialized_end=65
  _globals['_DETECTION']._serialized_start=67
  _globals['_DETECTION']._serialized_end=179
  _globals['_DETECTRESPONSE']._serialized_start=181
  _globals['_DETECTRESPONSE']._serialized_end=273
  _globals['_DETECTIONSERVICE']._serialized_start=275
  _globals['_DETECTIONSERVICE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
